python -m pip install requests
python -m pip install colorama
python -m pip install plyer
python -m pip install selenium
python -m pip install Pillow
python -m pip install PyAutoGUI
python -m pip install pyperclip
python -m pip install selenium
python -m pip install aiohttp
python -m pip install pypresence
python -m pip install pyinstaller
python -m pip install dhooks
python -m pip install lxml
python -m pip install comtypes
